module.exports={
    FEST_NAME:"festName",
    TEAM_DATA:"teamData",
    PROGRAMS:"programs",
    CALL_LISTS:"callLists",
    RESULTS:"results",
    TEAM_POINTS:"teamPoints",
    PENDING_RESULTS:"pendingResults",
    PUBLISHED:"published",
    PUBLISHED_TEAM:"publishedTeam",
    PUBLISHED_ZONE_TOPPERS:"publishedZoneToppers",
    INDIVIDUAL_POINTS:"individualPoints"
};